import config from 'config';

export default {
    SET_SESSION: 'SET_SESSION',
    SET_SESSION_SUCCESS: 'SET_SESSION_SUCCESS',
    SET_SESSION_FAIL: 'SET_SESSION_FAIL',
    UNSET_SESSION: 'UNSET_SESSION',
    UNSET_SESSION_SUCCESS: 'UNSET_SESSION_SUCCESS',
    UNSET_SESSION_FAIL: 'UNSET_SESSION_FAIL',

    GET_CAPABILITIES: 'GET_CAPABILITIES',
    GET_CAPABILITIES_SUCCESS: 'GET_CAPABILITIES_SUCCESS',
    GET_CAPABILITIES_FAIL: 'GET_CAPABILITIES_FAIL',

    GET_DOCUMENTATION: 'GET_DOCUMENTATION',
    GET_DOCUMENTATION_SUCCESS: 'GET_DOCUMENTATION_SUCCESS',
    GET_DOCUMENTATION_FAIL: 'GET_DOCUMENTATION_FAIL',

    SUBMIT_COMMAND: 'SUBMIT_COMMAND',
    SUBMIT_COMMAND_SUCCESS: 'SUBMIT_COMMAND_SUCCESS',
    SUBMIT_COMMAND_FAIL: 'SUBMIT_COMMAND_FAIL',

    GET_MINIONS: 'GET_MINIONS',
    GET_MINIONS_SUCCESS: 'GET_MINIONS_SUCCESS',
    GET_MINIONS_FAIL: 'GET_MINIONS_FAIL',

    GET_MINION: 'GET_MINION',
    GET_MINION_SUCCESS: 'GET_MINION_SUCCESS',
    GET_MINION_FAIL: 'GET_MINION_FAIL',

    GET_JOBS: 'GET_JOBS',
    GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
    GET_JOBS_FAIL: 'GET_JOBS_FAIL',

    GET_JOB: 'GET_JOB',
    GET_JOB_SUCCESS: 'GET_JOB_SUCCESS',
    GET_JOB_FAIL: 'GET_JOB_FAIL',

    SET_SETTING: 'SET_SETTING',
    CLEAR_SETTING: 'CLEAR_SETTING',
    
    SET_CLIENT_CONFIGURATION: 'SET_CLIENT_CONFIGURATION',
    SET_TARGET_CONFIGURATION: 'SET_TARGET_CONFIGURATION',
    SET_FUNCTION_CONFIGURATION: 'SET_FUNCTION_CONFIGURATION',

    TRANSITION: 'transition',

    SERVER_EVENT_RECEIVED: 'SERVER_EVENT_RECEIVED',
    CLEAR_EVENTS: 'CLEAR_EVENTS',

    STORE_COMMAND: 'STORE_COMMAND',
    CLEAR_COMMANDS: 'CLEAR_COMMANDS',
    CLEAR_COMMAND: 'CLEAR_COMMAND',

    DOCUMENTATION_TYPE: {
        EXECUTE: 'execution',
        RUNNER: 'runner',
        WHEEL: 'wheel'
    },

    URL: {
        ROOT: config.APP_BASE_URL + '/',
        LOGIN: config.APP_BASE_URL + '/login',
        JOB: config.APP_BASE_URL + '/job'
    }
};
